exclude: [
  'node_modules',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'sass',
  'sass-compiled.css',
  'bower_components',
  'README.md'
  ]

permalink: /:year/:title.html
ftp_host: simonsmith.io
ftp_dir: /public_html/new
ftp_passive: false
ftp_username: 'simon'
markdown: rdiscount
